language: python
python:
  - "3.6"
  - "3.7-dev"
sudo: false
install:
  - pip install pipenv
  - pipenv install --dev
  - echo 'export PYTHONPATH=${PYTHONPATH}:.' > .env
script:
  - pipenv run pycodestyle .
  - pipenv run flake8
  - pipenv run pytest -v .
